# Generated by Django 4.1.1 on 2024-06-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_country_options_movie_length_movie_title_cz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=64, null=True)),
                ('sex', models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('non-binary', 'Non Binary')], max_length=10, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.country')),
            ],
            options={
                'ordering': ['surname', 'name', 'birth_date'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='acting_in_movies', to='viewer.creator'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='directed_movies', to='viewer.creator'),
        ),
    ]
