# Generated by Django 4.1.1 on 2024-06-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_creator_movie_actors_movie_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
    ]
