# Generated by Django 4.1.1 on 2024-06-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
